# config.yml for pranala
name: Pranala
subtitle: "My personal ramblings and half-truth"
description: "Official home site Sindhu Kurnia, IoT tinkerer wannabe, casual coder and math lover."
keywords: tutorial, openwrt,linux, ham radio, jekyll, github
og:
   image: github.png
author: 
   name: Sindhu Kurnia
   fbid: https://www.facebook.com/sindhu.kurnia
url: https://prana.la
timezone: Asia/Jakarta
markdown: kramdown
highlighter: pygments
excerpt_separator: "<!-- more -->"

gems: [jekyll-paginate, jekyll-gist]

# Don't parse this to _site
exclude: ['Rakefile', 'Gemfile.lock', 'Gemfile', README.md, LICENSE]

# Permalinks format
permalink: /:year/:month/:day/:title/

# Pagination number of articles per page
paginate: 10

# Parameters required by generate_categories.rb plugin
category_dir: categories

# Disqus setting
disqus_shortname : prnla

# Google analytics setting
google_analytics : UA-37808923-4

#Facebook Apps ID
fb_appsid : 326012977514517

#Social Media Sharing Option
facebook_like: true
twitter_tweet_button: true
google_plus_one: true

#bitly short URL
bitly:
  username: prnla
  api_key: R_ae920ec1a2df97a41733f1ffd7c21c40
  
  
