name: Pranala
subtitle: "The random ramblings of a self-learner"
description: "Pranala is the home site of Sindhu Kurnia, casual programmer, tinkerer and math teacher."
keywords: tutorial, openwrt,linux, ham radio, jekyll, github
author: Sindhu Kurnia
url: http://prana.la
timezone: Asia/Jakarta
markdown: kramdown
highlighter: pygments

# Don't parse this to _site
exclude: ['Rakefile', 'Gemfile.lock', 'Gemfile', README.md, LICENSE]

# Permalinks format
permalink: /:year/:month/:day/:title/

# Pagination number of articles per page
paginate: 8

# Parameters required by generate_categories.rb plugin
category_dir: categories

# Disqus setting
disqus_shortname : prnla

# Google analytics setting
google_analytics : UA-37808923-4

