name: "Pranala"
description: ""
author: Sindhu Kurnia
url: "http://prana.la"
timezone: Asia/Jakarta
markdown: rdiscount
highlighter: pygments

# Don't parse this to _site
exclude: ['Rakefile', 'Gemfile.lock', 'Gemfile', README.md, LICENSE]

# Permalinks format
permalink: /:year/:month/:day/:title/

# Pagination number of articles per page
paginate: 5

# Parameters required by generate_categories.rb plugin
category_dir: categories

# Disqus setting
disqus_shortname : pranala

