name: Pranala
subtitle: "The random ramblings of a self-learner"
description: "Pranala is the home site of Sindhu Kurnia, tinkerer wannabe, casual coder and math lover."
keywords: tutorial, openwrt,linux, ham radio, jekyll, github
author: Sindhu Kurnia
url: http://prana.la
timezone: Asia/Jakarta
markdown: kramdown
highlighter: pygments
excerpt_separator: "<!-- more -->"

# Don't parse this to _site
exclude: ['Rakefile', 'Gemfile.lock', 'Gemfile', README.md, LICENSE]

# Permalinks format
permalink: /:year/:month/:day/:title/

# Pagination number of articles per page
paginate: 8

# Parameters required by generate_categories.rb plugin
category_dir: categories

# Disqus setting
disqus_shortname : prnla

# Google analytics setting
google_analytics : UA-37808923-4

# Glynn parameters
ftp_host: ftp.prana.la
ftp_dir: ~/domain/prana.la/prana.la/web/
ftp_passive: false

# optional
# ftp_port: 22                  	       # default 21
ftp_username: u10187ams@prana.la     # default read from stdin
ftp_password: F2exJEd96h5s        # default read from stdin
ftp_secure: true              	       # default false